default:
  golem_name: Trainingshiny
  golem_version: 0.0.0.9000
  app_prod: no
production:
  app_prod: yes
dev:
  golem_wd: C:/Users/Lisa P/Desktop/Autoformation/Codes-training/Shiny with golem/Trainingshiny
