# WARNING - Generated by {fusen} from /dev/flat_fonctions-metiers.Rmd: do not edit by hand

test_that("say_hello works", {

  expect_equal(object = say_hello(personne = "Hedia"),
               expected = "Hey coucou Hedia")

  expect_equal(object = say_hello(personne = "Margot"),
               expected = "Hey coucou Margot")
  #simple mais peut aussi faire des tests pour savoir si en entree prend bien en comtpe des chaines de caracteres, renvoi une erreur si ce nest pas le cas, ect
})
