# WARNING - Generated by {fusen} from /dev/flat_fonctions-metiers.Rmd: do not edit by hand

#' Dire bonjour a quelquun
#'
#' @param personne  Character, la personne a qui on souhaite dire bonjour
#'
#' @importFrom glue glue
#' @return Character, de type "Hey coucou {personne}
#' @export


#' @examples
#' say_hello(personne = "HÃ©dia")
#' say_hello(personne = "MickaÃ«l")
say_hello <- function(personne){
  glue("Hey coucou {personne}")
}

